### PR TITLE
Fixed search pattern in SolsticeClient.download.recipe

### PR DESCRIPTION
**Pull request by MLBZ521**
Fixed search pattern and made it an input variable
Fixed formatting

### CODE REVIEW

**Comment by MLBZ521** [comment]
If merged, this will fix issue #141.

**Comment by MLBZ521** [comment]
@joshua-d-miller Just bumping and tagging for visibility.

**Comment by joshua-d-miller** [comment]
Looks good. Thanks for this 👍

**Comment by MLBZ521** [comment]
Awesome, thanks!

**Pull request merged**
