### PR TITLE
Update NVivo.download.recipe

### PR DESCRIPTION
**Pull request by paul-cossey**
Hi

This PR adds in the Addition of CodeSignatureVerifier

-vvv output 

```
autopkg run -vvv /Users/paul/Documents/GitHub/joshua-d-miller-recipes/NVivo/NVivo.download.recipe 
Processing /Users/paul/Documents/GitHub/joshua-d-miller-recipes/NVivo/NVivo.download.recipe...
WARNING: /Users/paul/Documents/GitHub/joshua-d-miller-recipes/NVivo/NVivo.download.recipe is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
{'AUTOPKG_VERSION': '2.3.1',
 'GIT_PATH': '/Applications/Xcode.app/Contents/Developer/usr/bin/git',
 'MUNKI_REPO': '/Users/Shared/munki_repo',
 'NAME': 'NVivo',
 'PARENT_RECIPES': [],
 'RECIPE_CACHE_DIR': '/Users/paul/Library/AutoPkg/Cache/com.github.joshua-d-miller.download.nvivo',
 'RECIPE_DIR': '/Users/paul/Documents/GitHub/joshua-d-miller-recipes/NVivo',
 'RECIPE_OVERRIDE_DIRS': ['~/Library/AutoPkg/RecipeOverrides'],
 'RECIPE_PATH': '/Users/paul/Documents/GitHub/joshua-d-miller-recipes/NVivo/NVivo.download.recipe',
 'RECIPE_REPOS': {},
 'RECIPE_REPO_DIR': '/Users/Shared/munki_repo',
 'RECIPE_SEARCH_DIRS': ['.',
                        '~/Library/AutoPkg/Recipes',
                        '/Library/AutoPkg/Recipes'],
 'verbose': 3}
URLDownloader
{'Input': {'filename': 'NVivo.dmg',
           'url': 'http://download.qsrinternational.com/Software/NVivoforMac/NVivo.dmg'}}
URLDownloader: No value supplied for prefetch_filename, setting default value of: False
URLDownloader: No value supplied for CHECK_FILESIZE_ONLY, setting default value of: False
URLDownloader: Storing new Last-Modified header: Mon, 28 Mar 2022 04:43:09 GMT
URLDownloader: Storing new ETag header: "e3ebd4e2141e6b239fd0692ec5a3ec9b-132"
URLDownloader: Downloaded /Users/paul/Library/AutoPkg/Cache/com.github.joshua-d-miller.download.nvivo/downloads/NVivo.dmg
{'Output': {'download_changed': True,
            'etag': '"e3ebd4e2141e6b239fd0692ec5a3ec9b-132"',
            'last_modified': 'Mon, 28 Mar 2022 04:43:09 GMT',
            'pathname': '/Users/paul/Library/AutoPkg/Cache/com.github.joshua-d-miller.download.nvivo/downloads/NVivo.dmg',
            'url_downloader_summary_result': {'data': {'download_path': '/Users/paul/Library/AutoPkg/Cache/com.github.joshua-d-miller.download.nvivo/downloads/NVivo.dmg'},
                                              'summary_text': 'The following '
                                                              'new items were '
                                                              'downloaded:'}}}
EndOfCheckPhase
{'Input': {}}
{'Output': {}}
CodeSignatureVerifier
{'Input': {'input_path': '/Users/paul/Library/AutoPkg/Cache/com.github.joshua-d-miller.download.nvivo/downloads/NVivo.dmg/NVivo.app',
           'requirement': 'identifier "com.qsrinternational.NVivo-20" and '
                          'anchor apple generic and certificate '
                          '1[field.1.2.840.113635.100.6.2.6] /* exists */ and '
                          'certificate leaf[field.1.2.840.113635.100.6.1.13] '
                          '/* exists */ and certificate leaf[subject.OU] = '
                          'A66L57342X'}}
CodeSignatureVerifier: Mounted disk image /Users/paul/Library/AutoPkg/Cache/com.github.joshua-d-miller.download.nvivo/downloads/NVivo.dmg
CodeSignatureVerifier: Verifying code signature...
CodeSignatureVerifier: Deep verification enabled...
CodeSignatureVerifier: Strict verification not defined. Using codesign defaults...
CodeSignatureVerifier: /private/tmp/dmg.0KWbdV/NVivo.app: valid on disk
CodeSignatureVerifier: /private/tmp/dmg.0KWbdV/NVivo.app: satisfies its Designated Requirement
CodeSignatureVerifier: /private/tmp/dmg.0KWbdV/NVivo.app: explicit requirement satisfied
CodeSignatureVerifier: Signature is valid
{'Output': {}}
{'AUTOPKG_VERSION': '2.3.1',
 'CHECK_FILESIZE_ONLY': False,
 'GIT_PATH': '/Applications/Xcode.app/Contents/Developer/usr/bin/git',
 'MUNKI_REPO': '/Users/Shared/munki_repo',
 'NAME': 'NVivo',
 'PARENT_RECIPES': [],
 'RECIPE_CACHE_DIR': '/Users/paul/Library/AutoPkg/Cache/com.github.joshua-d-miller.download.nvivo',
 'RECIPE_DIR': '/Users/paul/Documents/GitHub/joshua-d-miller-recipes/NVivo',
 'RECIPE_OVERRIDE_DIRS': ['~/Library/AutoPkg/RecipeOverrides'],
 'RECIPE_PATH': '/Users/paul/Documents/GitHub/joshua-d-miller-recipes/NVivo/NVivo.download.recipe',
 'RECIPE_REPOS': {},
 'RECIPE_REPO_DIR': '/Users/Shared/munki_repo',
 'RECIPE_SEARCH_DIRS': ['.',
                        '~/Library/AutoPkg/Recipes',
                        '/Library/AutoPkg/Recipes'],
 'download_changed': True,
 'etag': '"e3ebd4e2141e6b239fd0692ec5a3ec9b-132"',
 'filename': 'NVivo.dmg',
 'input_path': '/Users/paul/Library/AutoPkg/Cache/com.github.joshua-d-miller.download.nvivo/downloads/NVivo.dmg/NVivo.app',
 'last_modified': 'Mon, 28 Mar 2022 04:43:09 GMT',
 'pathname': '/Users/paul/Library/AutoPkg/Cache/com.github.joshua-d-miller.download.nvivo/downloads/NVivo.dmg',
 'prefetch_filename': False,
 'requirement': 'identifier "com.qsrinternational.NVivo-20" and anchor apple '
                'generic and certificate 1[field.1.2.840.113635.100.6.2.6] /* '
                'exists */ and certificate '
                'leaf[field.1.2.840.113635.100.6.1.13] /* exists */ and '
                'certificate leaf[subject.OU] = A66L57342X',
 'url': 'http://download.qsrinternational.com/Software/NVivoforMac/NVivo.dmg',
 'url_downloader_summary_result': {'data': {'download_path': '/Users/paul/Library/AutoPkg/Cache/com.github.joshua-d-miller.download.nvivo/downloads/NVivo.dmg'},
                                   'summary_text': 'The following new items '
                                                   'were downloaded:'},
 'verbose': 3}
Receipt written to /Users/paul/Library/AutoPkg/Cache/com.github.joshua-d-miller.download.nvivo/receipts/NVivo.download-receipt-20220421-093058.plist

The following new items were downloaded:
    Download Path                                                                                    
    -------------                                                                                    
    /Users/paul/Library/AutoPkg/Cache/com.github.joshua-d-miller.download.nvivo/downloads/NVivo.dmg
```

### CODE REVIEW

**Comment by joshua-d-miller** [comment]
This looks great however I noticed the identifier has 20 in it. I know NVivo's versioning has been a little odd. Should we maybe remove the identifier and just look for the certificate?

**Comment by paul-cossey** [comment]
Yes it does, I was tempted run with separate v20 recipes, but decided against the unnecessary duplication. 

I'm happy to look at the cert rather than the identifier. 😄 

I can make the changes tomorrow (it's getting late here in the UK)

**Comment by paul-cossey** [comment]
Hi, @joshua-d-miller 

I've just removed the identifier from CodeSignatureVerifier. 

-vvv output 

```
autopkg run -vvv /Users/paul/Documents/GitHub/joshua-d-miller-recipes/NVivo/NVivo.download.recipe 
Processing /Users/paul/Documents/GitHub/joshua-d-miller-recipes/NVivo/NVivo.download.recipe...
WARNING: /Users/paul/Documents/GitHub/joshua-d-miller-recipes/NVivo/NVivo.download.recipe is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
{'AUTOPKG_VERSION': '2.3.1',
 'GIT_PATH': '/Applications/Xcode.app/Contents/Developer/usr/bin/git',
 'MUNKI_REPO': '/Users/Shared/munki_repo',
 'NAME': 'NVivo',
 'PARENT_RECIPES': [],
 'RECIPE_CACHE_DIR': '/Users/paul/Library/AutoPkg/Cache/com.github.joshua-d-miller.download.nvivo',
 'RECIPE_DIR': '/Users/paul/Documents/GitHub/joshua-d-miller-recipes/NVivo',
 'RECIPE_OVERRIDE_DIRS': ['~/Library/AutoPkg/RecipeOverrides'],
 'RECIPE_PATH': '/Users/paul/Documents/GitHub/joshua-d-miller-recipes/NVivo/NVivo.download.recipe',
 'RECIPE_REPOS': {},
 'RECIPE_REPO_DIR': '/Users/Shared/munki_repo',
 'RECIPE_SEARCH_DIRS': ['.',
                        '~/Library/AutoPkg/Recipes',
                        '/Library/AutoPkg/Recipes'],
 'verbose': 3}
URLDownloader
{'Input': {'filename': 'NVivo.dmg',
           'url': 'http://download.qsrinternational.com/Software/NVivoforMac/NVivo.dmg'}}
URLDownloader: No value supplied for prefetch_filename, setting default value of: False
URLDownloader: No value supplied for CHECK_FILESIZE_ONLY, setting default value of: False
URLDownloader: Storing new Last-Modified header: Mon, 28 Mar 2022 04:43:09 GMT
URLDownloader: Storing new ETag header: "e3ebd4e2141e6b239fd0692ec5a3ec9b-132"
URLDownloader: Downloaded /Users/paul/Library/AutoPkg/Cache/com.github.joshua-d-miller.download.nvivo/downloads/NVivo.dmg
{'Output': {'download_changed': True,
            'etag': '"e3ebd4e2141e6b239fd0692ec5a3ec9b-132"',
            'last_modified': 'Mon, 28 Mar 2022 04:43:09 GMT',
            'pathname': '/Users/paul/Library/AutoPkg/Cache/com.github.joshua-d-miller.download.nvivo/downloads/NVivo.dmg',
            'url_downloader_summary_result': {'data': {'download_path': '/Users/paul/Library/AutoPkg/Cache/com.github.joshua-d-miller.download.nvivo/downloads/NVivo.dmg'},
                                              'summary_text': 'The following '
                                                              'new items were '
                                                              'downloaded:'}}}
EndOfCheckPhase
{'Input': {}}
{'Output': {}}
CodeSignatureVerifier
{'Input': {'input_path': '/Users/paul/Library/AutoPkg/Cache/com.github.joshua-d-miller.download.nvivo/downloads/NVivo.dmg/NVivo.app',
           'requirement': 'anchor apple generic and certificate '
                          '1[field.1.2.840.113635.100.6.2.6] /* exists */ and '
                          'certificate leaf[field.1.2.840.113635.100.6.1.13] '
                          '/* exists */ and certificate leaf[subject.OU] = '
                          'A66L57342X'}}
CodeSignatureVerifier: Mounted disk image /Users/paul/Library/AutoPkg/Cache/com.github.joshua-d-miller.download.nvivo/downloads/NVivo.dmg
CodeSignatureVerifier: Verifying code signature...
CodeSignatureVerifier: Deep verification enabled...
CodeSignatureVerifier: Strict verification not defined. Using codesign defaults...
CodeSignatureVerifier: /private/tmp/dmg.IxH97w/NVivo.app: valid on disk
CodeSignatureVerifier: /private/tmp/dmg.IxH97w/NVivo.app: satisfies its Designated Requirement
CodeSignatureVerifier: /private/tmp/dmg.IxH97w/NVivo.app: explicit requirement satisfied
CodeSignatureVerifier: Signature is valid
{'Output': {}}
{'AUTOPKG_VERSION': '2.3.1',
 'CHECK_FILESIZE_ONLY': False,
 'GIT_PATH': '/Applications/Xcode.app/Contents/Developer/usr/bin/git',
 'MUNKI_REPO': '/Users/Shared/munki_repo',
 'NAME': 'NVivo',
 'PARENT_RECIPES': [],
 'RECIPE_CACHE_DIR': '/Users/paul/Library/AutoPkg/Cache/com.github.joshua-d-miller.download.nvivo',
 'RECIPE_DIR': '/Users/paul/Documents/GitHub/joshua-d-miller-recipes/NVivo',
 'RECIPE_OVERRIDE_DIRS': ['~/Library/AutoPkg/RecipeOverrides'],
 'RECIPE_PATH': '/Users/paul/Documents/GitHub/joshua-d-miller-recipes/NVivo/NVivo.download.recipe',
 'RECIPE_REPOS': {},
 'RECIPE_REPO_DIR': '/Users/Shared/munki_repo',
 'RECIPE_SEARCH_DIRS': ['.',
                        '~/Library/AutoPkg/Recipes',
                        '/Library/AutoPkg/Recipes'],
 'download_changed': True,
 'etag': '"e3ebd4e2141e6b239fd0692ec5a3ec9b-132"',
 'filename': 'NVivo.dmg',
 'input_path': '/Users/paul/Library/AutoPkg/Cache/com.github.joshua-d-miller.download.nvivo/downloads/NVivo.dmg/NVivo.app',
 'last_modified': 'Mon, 28 Mar 2022 04:43:09 GMT',
 'pathname': '/Users/paul/Library/AutoPkg/Cache/com.github.joshua-d-miller.download.nvivo/downloads/NVivo.dmg',
 'prefetch_filename': False,
 'requirement': 'anchor apple generic and certificate '
                '1[field.1.2.840.113635.100.6.2.6] /* exists */ and '
                'certificate leaf[field.1.2.840.113635.100.6.1.13] /* exists '
                '*/ and certificate leaf[subject.OU] = A66L57342X',
 'url': 'http://download.qsrinternational.com/Software/NVivoforMac/NVivo.dmg',
 'url_downloader_summary_result': {'data': {'download_path': '/Users/paul/Library/AutoPkg/Cache/com.github.joshua-d-miller.download.nvivo/downloads/NVivo.dmg'},
                                   'summary_text': 'The following new items '
                                                   'were downloaded:'},
 'verbose': 3}
Receipt written to /Users/paul/Library/AutoPkg/Cache/com.github.joshua-d-miller.download.nvivo/receipts/NVivo.download-receipt-20220428-154841.plist

The following new items were downloaded:
    Download Path                                                                                    
    -------------                                                                                    
    /Users/paul/Library/AutoPkg/Cache/com.github.joshua-d-miller.download.nvivo/downloads/NVivo.dmg  
```

**Comment by joshua-d-miller** [comment]
This looks great! I'll go ahead and merge :)

**Pull request merged**
