### PR TITLE
Update Zotero download recipe

### PR DESCRIPTION
**Pull request by bochoven**
The url has changed

### CODE REVIEW

**Comment by octomike** [comment]
the DOM part containing the download URL is generated with javascript, so this won't work I guess

**Comment by octomike** [comment]
This works for me:

```patch
--- a/Zotero/Zotero.download.recipe
+++ b/Zotero/Zotero.download.recipe
@@ -23,7 +23,7 @@
                                <key>url</key>
                                <string>https://www.zotero.org/download/</string>
                                <key>re_pattern</key>
-                               <string>(?P&lt;url&gt;download.zotero.org/standalone/.*?/Zotero-.*?\.dmg)</string>
+                               <string>{"standaloneVersions":[^}]+"mac":"(?P&lt;version&gt;[^"]+)[^}]+}</string>
                        </dict>
                </dict>
                <dict>
@@ -32,7 +32,7 @@
                        <key>Arguments</key>
                        <dict>
                                <key>url</key>
-                               <string>https://%url%</string>
+                               <string>https://www.zotero.org/download/client/dl?channel=release&amp;platform=mac&amp;version=%version%</string>
                                <key>filename</key>
                                <string>%NAME%.dmg</string>
                        </dict>
```

**Comment by bochoven** [comment]
For posterity: I did some digging into the auto update mechanism of zotero. It uses the same mechanism as the Mozilla apps. Using this URL `https://www.zotero.org/download/standalone/update/3.0a8pre/2007083015/Darwin_x86-gcc3/en-US/release/Darwin%208.10.1/update.xml` results in an XML file that contains a link to a `.mar` file. This is a Mozilla Archive which is used by the Mozilla updater to patch a program. I don't feel that this leads anywhere, so scraping the webpage seems to be the best option at the moment.

**Comment by bochoven** [comment]
https://github.com/zotero/zotero-standalone-build/issues/56

**Comment by bochoven** [comment]
Closing if favour of #33

**Pull request closed without merging**
